export const MASTERDATA_RREQUEST = 'MASTERDATA_RREQUEST';
export type MASTERDATA_RREQUEST = typeof MASTERDATA_RREQUEST;

export const MASTERDATA_RECEIVE = 'MASTERDATA_RECEIVE';
export type MASTERDATA_RECEIVE = typeof MASTERDATA_RECEIVE;

export const MASTERDATA_FETCH = 'MASTERDATA_FETCH';
export type MASTERDATA_FETCH = typeof MASTERDATA_FETCH;