export const MASTERDATA_REQUEST = 'MASTERDATA_REQUEST';
export type MASTERDATA_REQUEST = typeof MASTERDATA_REQUEST;

export const MASTERDATA_RECEIVE = 'MASTERDATA_RECEIVE';
export type MASTERDATA_RECEIVE = typeof MASTERDATA_RECEIVE;

export const MASTERDATA_FETCH = 'MASTERDATA_FETCH';
export type MASTERDATA_FETCH = typeof MASTERDATA_FETCH;

export const MASTERDATA_ERROR = 'MASTERDATA_ERROR';
export type MASTERDATA_ERROR = typeof MASTERDATA_ERROR;